apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.stage-prefix }}-doctors-directory-server-deployment
  namespace: {{ .Values.namespace }}-doctors-directory
  labels:
    app: {{ .Values.stage-prefix }}-doctors-directory-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.stage-prefix }}-doctors-directory-server
  template:
    metadata:
      namespace: {{ .Values.namespace }}-doctors-directory
      labels:
        app: {{ .Values.stage-prefix }}-doctors-directory-server
    spec:
      containers:
        - name: {{ .Values.stage-prefix }}-doctors-directory-server
          image: tm63/doctors-directory-gql-node-js-server:migration-script-int-commit
          ports:
            - containerPort: 5002
          env:
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.stage-prefix }}-doctors-directory-server-configmap
                  key: database_host

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.stage-prefix }}-doctors-directory-server-service
  namespace: {{ .Values.namespace }}-doctors-directory
spec:
  selector:
    app: {{ .Values.stage-prefix }}-doctors-directory-server
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002