apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.stagePrefix }}-doctors-directory-client-configmap-{{ .Release.Name }}
  namespace: {{ .Values.namespace }}-doctors-directory-{{ .Release.Name }}
data:
  server_host: localhost