apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.stagePrefix }}-doctors-directory-client-deployment-{{ .Release.Name }}
  namespace: {{ .Values.namespace }}-doctors-directory-{{ .Release.Name }}
  labels:
    app: {{ .Values.stagePrefix }}-doctors-directory-client-{{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.stagePrefix }}-doctors-directory-client-{{ .Release.Name }}
  template:
    metadata:
      namespace: {{ .Values.namespace }}-doctors-directory-{{ .Release.Name }}
      labels:
        app: {{ .Values.stagePrefix }}-doctors-directory-client-{{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Values.stagePrefix }}-doctors-directory-client-{{ .Release.Name }}
          image: {{ .Values.doctorsDirectoryClient.deployment.repository }}/{{ .Values.doctorsDirectoryClient.deployment.image  }}:{{ .Values.doctorsDirectoryClient.deployment.tag  }}
          ports:
            - containerPort: {{ .Values.doctorsDirectoryClient.deployment.containerPort }}
          env:
            - name: REACT_APP_SERVER_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.stagePrefix }}-doctors-directory-client-configmap-{{ .Release.Name }}
                  key: server_host

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.stagePrefix }}-doctors-directory-client-service-{{ .Release.Name }}
  namespace: {{ .Values.namespace }}-doctors-directory-{{ .Release.Name }}
spec:
  selector:
    app: {{ .Values.stagePrefix }}-doctors-directory-client-{{ .Release.Name }}
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000