apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.stage-prefix }}-doctors-directory-server-configmap
  namespace: {{ .Values.namespace }}-doctors-directory
data:
  database_host: mongodb-service