apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.stage-prefix }}-mongodb-deployment-{{ .Release.Name }}"
  namespace: "{{ .Values.namespace }}-doctors-directory-{{ .Release.Name }}"
  labels:
    app: "{{ .Values.stage-prefix }}-mongodb-{{ .Release.Name }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Values.stage-prefix }}-mongodb-{{ .Release.Name }}"
  template:
    metadata:
      namespace: "{{ .Values.namespace }}-doctors-directory-{{ .Release.Name }}"
      labels:
        app: "{{ .Values.stage-prefix }}-mongodb-{{ .Release.Name }}"
    spec:
      containers:
        - name: "{{ .Values.stage-prefix }}-mongo-{{ .Release.Name }}"
          image: mongo
          ports:
            - containerPort: 27017

---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.stage-prefix }}-mongodb-service-{{ .Release.Name }}"
  namespace: "{{ .Values.namespace }}-doctors-directory-{{ .Release.Name }}"
spec:
  selector:
    app: "{{ .Values.stage-prefix }}-mongodb-{{ .Release.Name }}"
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017