apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.stagePrefix }}-mongodb-deployment-{{ .Release.Name }}
  namespace: {{ .Values.namespace }}-doctors-directory-{{ .Release.Name }}
  labels:
    app: {{ .Values.stagePrefix }}-mongodb-{{ .Release.Name }}
spec:
  replicas: {{ .Values.doctorsDirectoryDatabase.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.stagePrefix }}-mongodb-{{ .Release.Name }}
  template:
    metadata:
      namespace: {{ .Values.namespace }}-doctors-directory-{{ .Release.Name }}
      labels:
        app: {{ .Values.stagePrefix }}-mongodb-{{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Values.stagePrefix }}-mongo-{{ .Release.Name }}
          image: {{ .Values.doctorsDirectoryDatabase.deployment.image  }}
          ports:
            - containerPort: {{ .Values.doctorsDirectoryDatabase.deployment.containerPort }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.stagePrefix }}-mongodb-service-{{ .Release.Name }}
  namespace: {{ .Values.namespace }}-doctors-directory-{{ .Release.Name }}
spec:
  selector:
    app: {{ .Values.stagePrefix }}-mongodb-{{ .Release.Name }}
  ports:
    - protocol: {{ .Values.doctorsDirectoryDatabase.service.protocol }}
      port: {{ .Values.doctorsDirectoryDatabase.service.port }}
      targetPort: {{ .Values.doctorsDirectoryDatabase.service.targetPort }}