apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.stagePrefix }}-mongodb-deployment-{{ .Release.Name }}
  namespace: {{ .Values.namespace }}-doctors-directory-{{ .Release.Name }}
  labels:
    app: {{ .Values.stagePrefix }}-mongodb-{{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.stagePrefix }}-mongodb-{{ .Release.Name }}
  template:
    metadata:
      namespace: {{ .Values.namespace }}-doctors-directory-{{ .Release.Name }}
      labels:
        app: {{ .Values.stagePrefix }}-mongodb-{{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Values.stagePrefix }}-mongo-{{ .Release.Name }}
          image: mongo
          ports:
            - containerPort: 27017

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.stagePrefix }}-mongodb-service-{{ .Release.Name }}
  namespace: {{ .Values.namespace }}-doctors-directory-{{ .Release.Name }}
spec:
  selector:
    app: {{ .Values.stagePrefix }}-mongodb-{{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017