apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.stage-prefix }}-mongodb-deployment
  namespace: {{ .Values.namespace }}-doctors-directory
  labels:
    app: {{ .Values.stage-prefix }}-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.stage-prefix }}-mongodb
  template:
    metadata:
      namespace: {{ .Values.namespace }}-doctors-directory
      labels:
        app: {{ .Values.stage-prefix }}-mongodb
    spec:
      containers:
        - name: {{ .Values.stage-prefix }}-mongo
          image: mongo
          ports:
            - containerPort: 27017

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.stage-prefix }}-mongodb-service
  namespace: {{ .Values.namespace }}-doctors-directory
spec:
  selector:
    app: {{ .Values.stage-prefix }}-mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017