apiVersion: v2
name: doctors-directory-chart
description: This is my first-attempt at working with Helm Charts.
type: application
version: 0.1.0
appVersion: "1.16.0"
maintainers:
- email: tluwani2020@gmail.com
  name: TluwaniMS
