namespace: 'dev-space'

stage-prefix: 'dev'

doctors-directory-client:
  deployment:
  configmap:
  service:

doctors-directory-server:
  deployment:
  configmap:
  service:

doctors-directory-database:
  deployment:
  service: