namespace: 'prod-space'

stagePrefix: 'prod'

doctors-directory-client:
  deployment:
  configmap:
  service:

doctors-directory-server:
  deployment:
  configmap:
  service:

doctors-directory-database:
  deployment:
  service: